spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: Demo-E-Commerce
  datasource:
    url: jdbc:mysql://localhost:3306/e_commerce_management
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:123456}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
jwt:
  secret-key: ${JWT_SECRET_KEY}
  issuer: http://localhost:8080

web:
  admin:
    username: ${ADMIN_USERNAME}
    password: ${ADMIN_PASSWORD}
    phone: ${ADMIN_PHONE_NUMBER}

client:
  frontend-url: http://localhost:3000
