spring:
  application:
    name: Demo-E-Commerce
  datasource:
    url: jdbc:mysql://localhost:3306/e_commerce_management
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:123456}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
  flyway:
    locations: classpath:db/migration
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - openid
              - email
              - profile
jwt:
  secret-key: ${JWT_SECRET_KEY}
  issuer: http://localhost:8080

web:
  admin:
    username: ${ADMIN_USERNAME}
    password: ${ADMIN_PASSWORD}
    phone: ${ADMIN_PHONE_NUMBER}

client:
  frontend-url: http://localhost:3000

sendgrid:
  api-key: ${SENDGRID_API_KEY}
  from-email: ${SENDGRID_FROM_MAIL}
  from-name: ${SENDGRID_FROM_NAME:Gearhouse}
  template-id:
    welcome: d-5eb0c80c3651446fa71f97a8158eba86
    reset-password: d-68a654d772ec47e6ae9dacefc28375e0

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html